import { useState, type FormEvent } from 'react'
import { Save, X } from 'lucide-react'
import { api } from '../../api'
import { emptyArticle } from '../../constants'
import type { Article } from '../../types'

interface ArticleEditorProps { article?: Article; onClose: () => void; onSaved: () => void }

export function ArticleEditor({ article, onClose, onSaved }: ArticleEditorProps) {
  const [form, setForm] = useState<Partial<Article>>(article || emptyArticle)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const change = (key: keyof Article, value: string | boolean) => setForm(current => ({ ...current, [key]: value }))
  const upload = async (file?: File) => { if (!file) return; setBusy(true); try { const result = await api.uploadImage(file); change('imageUrl', result.imageUrl) } catch (requestError) { setError((requestError as Error).message) } finally { setBusy(false) } }
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await api.saveArticle(form); onSaved() } catch (requestError) { setError((requestError as Error).message) } finally { setBusy(false) } }
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-ink/60 p-4 sm:p-8"><form onSubmit={submit} className="mx-auto max-w-3xl bg-paper p-6 shadow-2xl sm:p-10"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-clay">Editor</p><h2 className="mt-1 font-display text-3xl">{article ? 'Editar artículo' : 'Nueva historia'}</h2></div><button type="button" aria-label="Cerrar" onClick={onClose}><X /></button></div><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="text-sm sm:col-span-2">Título<input className="editor-input mt-2" value={form.title || ''} onChange={event => change('title', event.target.value)} required /></label><label className="text-sm">Autor<input className="editor-input mt-2" value={form.author || ''} onChange={event => change('author', event.target.value)} required /></label><label className="text-sm">Categoría<input className="editor-input mt-2" value={form.category || ''} onChange={event => change('category', event.target.value)} required /></label><label className="text-sm sm:col-span-2">Resumen<textarea className="editor-input mt-2 min-h-24" value={form.excerpt || ''} onChange={event => change('excerpt', event.target.value)} required /></label><label className="text-sm sm:col-span-2">Contenido<textarea className="editor-input mt-2 min-h-64" value={form.content || ''} onChange={event => change('content', event.target.value)} required /></label><label className="text-sm sm:col-span-2">Imagen<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" className="editor-input mt-2" onChange={event => upload(event.target.files?.[0])} /></label>{form.imageUrl && <img src={form.imageUrl} alt="Vista previa" className="h-52 w-full object-cover sm:col-span-2" />}<label className="text-sm sm:col-span-2">Texto alternativo<input className="editor-input mt-2" value={form.imageAlt || ''} onChange={event => change('imageAlt', event.target.value)} required /></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={form.published ?? true} onChange={event => change('published', event.target.checked)} /> Publicado</label></div>{error && <p className="mt-5 text-sm text-clay">{error}</p>}<div className="mt-8 flex justify-end gap-3"><button type="button" onClick={onClose} className="border border-ink/20 px-5 py-3">Cancelar</button><button disabled={busy} className="flex items-center gap-2 bg-clay px-5 py-3 font-semibold text-white disabled:opacity-50"><Save size={17} /> Guardar</button></div></form></div>
}
