import mongoose from 'mongoose'
import { config } from './config.js'
import { Article, Image, SiteSettings } from './models.js'
import { createSlug } from './utils.js'

const stories = [
  { title: 'La ciudad que aprendió a escuchar el río', category: 'Crónica', excerpt: 'Vecinos, científicos y pescadores reconstruyen una relación perdida con el paisaje que los rodea.', colors: ['#74806a', '#d8c9a8'], content: 'Durante décadas, el río fue apenas una línea en el mapa. Una frontera discreta entre barrios que crecieron dándole la espalda.\n\nAhora, un grupo de vecinos vuelve a caminar sus orillas. Miden el agua, registran aves y recuperan historias que parecían destinadas al olvido.\n\nEste cambio no nació de una gran obra, sino de pequeñas conversaciones sostenidas en el tiempo. Una forma de periodismo local que observa, pregunta y acompaña.' },
  { title: 'El oficio invisible detrás de cada madrugada', category: 'Sociedad', excerpt: 'Retrato de quienes ponen en marcha la ciudad mucho antes de que suene el primer despertador.', colors: ['#43525a', '#c4a66b'], content: 'A las cuatro de la mañana la ciudad tiene otro ritmo. Las avenidas están vacías, pero en mercados, hornos y terminales el día ya comenzó.\n\nSus protagonistas rara vez aparecen en las estadísticas. Sin embargo, cada una de sus tareas sostiene una cadena de gestos cotidianos.\n\nDurante una semana seguimos ese turno silencioso para entender cómo se vive cuando el reloj de todos los demás todavía duerme.' },
  { title: 'Bibliotecas pequeñas, comunidades enormes', category: 'Cultura', excerpt: 'En pueblos alejados, una red de bibliotecas populares crea espacios de encuentro y memoria.', colors: ['#9b5d48', '#d6ba8b'], content: 'La puerta abre tres tardes por semana. Adentro hay novelas, manuales, periódicos viejos y una mesa grande en la que siempre cabe alguien más.\n\nLas bibliotecas populares son mucho más que estantes. Funcionan como archivo, refugio y plaza pública.\n\nEsta historia recorre tres pueblos y las personas que decidieron defender el derecho a leer cerca de casa.' },
  { title: 'La economía de reparar en vez de desechar', category: 'Economía', excerpt: 'Talleres y cooperativas están convirtiendo objetos rotos en trabajo, aprendizaje y una segunda oportunidad.', colors: ['#7a7162', '#bbc1a3'], content: 'Una tostadora, una bicicleta, un teléfono. Objetos cotidianos que suelen terminar demasiado pronto en la basura.\n\nEn distintos barrios aparecen talleres donde reparar vuelve a ser una práctica compartida. Allí circula conocimiento, se reduce el desperdicio y nacen nuevos oficios.\n\nNo se trata de nostalgia. Es una respuesta concreta a un modelo de consumo que ya muestra sus límites.' },
]

function svg(title: string, colors: string[]) { return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="900"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${colors[0]}"/><stop offset="1" stop-color="${colors[1]}"/></linearGradient><filter id="n"><feTurbulence baseFrequency=".8" numOctaves="3" stitchTiles="stitch"/><feBlend in="SourceGraphic" mode="soft-light"/></filter></defs><rect width="100%" height="100%" fill="url(#g)"/><rect width="100%" height="100%" filter="url(#n)" opacity=".16"/><circle cx="1050" cy="280" r="240" fill="#f4f1e9" opacity=".12"/><path d="M0 720 Q350 500 700 700 T1400 620 V900 H0Z" fill="#181916" opacity=".18"/><text x="80" y="800" fill="#fff" opacity=".8" font-family="Georgia" font-size="36">${title.replace(/[&<>]/g, '')}</text></svg>`) }

async function seed() {
  await mongoose.connect(config.mongoUri)
  await SiteSettings.findOneAndUpdate({ key: 'main' }, { key: 'main', siteName: 'Bellas', eyebrow: 'Historias que merecen tiempo', heroTitle: 'Periodismo para mirar más de cerca.', heroText: 'Crónicas, conversaciones y análisis independientes sobre las personas y los lugares que transforman nuestro presente.', bannerText: 'Nueva edición · Historias locales, preguntas universales', aboutText: 'Bellas es un medio independiente que apuesta por la pausa, la curiosidad y el contexto. Publicamos historias hechas con tiempo y cerca de sus protagonistas.' }, { upsert: true, new: true })
  if (await Article.countDocuments()) { console.log('La base ya contiene artículos; no se modificaron.'); await mongoose.disconnect(); return }
  for (const [position, story] of stories.entries()) { const image = await Image.create({ data: svg(story.title, story.colors), contentType: 'image/svg+xml', filename: `${createSlug(story.title)}.svg` }); await Article.create({ title: story.title, slug: createSlug(story.title), excerpt: story.excerpt, content: story.content, author: 'Sebastián Bellas', category: story.category, imageId: image._id, imageAlt: `Ilustración para ${story.title}`, position, published: true, publishedAt: new Date(Date.now() - position * 86400000 * 4) }) }
  console.log('Contenido inicial creado.')
  await mongoose.disconnect()
}

seed().catch(error => { console.error(error); process.exit(1) })
